In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/osaka.csv')

In [4]:
df

,date,mean temperature,maximum temperature,minimum temperature,rainfall,daylight,steam pressure,cloudiness,wind spped,fallen snow
0,2022/1/1,3.8,7.2,1.9,0.0,4.7,4.9,7.8,2.3,0
1,2022/1/2,4.8,9.5,-0.1,0.0,9.0,5.5,1.5,1.5,0
2,2022/1/3,7.7,11.5,3.5,0.0,9.0,5.8,3.5,1.8,0
3,2022/1/4,7.1,9.9,4.5,0.0,3.3,5.7,7.0,3.0,0
4,2022/1/5,4.9,8.1,3.1,0.0,2.6,5.1,7.3,2.0,0
...,...,...,...,...,...,...,...,...,...,...
360,2022/12/27,7.5,11.1,3.7,0.0,5.0,5.8,4.3,1.7,0
361,2022/12/28,7.0,11.8,1.7,0.0,8.2,6.8,2.0,1.6,0
362,2022/12/29,8.1,11.0,5.6,0.0,8.9,5.7,1.8,2.3,0
363,2022/12/30,6.5,10.5,2.1,0.0,6.9,4.9,2.5,1.8,0
364,2022/12/31,7.2,11.7,2.5,0.0,7.8,5.5,3.8,1.8,0