# 先端系課題_005

In [4]:
import pandas as pd
from pycaret.classification import *
train_data = pd.read_csv("./data/train.csv")

In [5]:
#前処理
exp_data = setup(data = train_data, target = 'Survived', session_id=123)

In [7]:
# モデルの比較
best_model = compare_models()

In [9]:
print(best_model)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [11]:
#モデル作成
lightgbm = create_model('lightgbm')

In [13]:
# catboostのモデルを最適化
lightgbm_tuned = tune_model(lightgbm)

In [14]:
# 解析結果の確認
evaluate_model(lightgbm_tuned)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [18]:
# アンサンブル学習
lgbm = create_model('lightgbm')
xgboost = create_model('gbc')

ensemble = blend_models([lgbm, xgboost])

In [19]:
test_pred = predict_model(lightgbm_tuned)

## 分析結果

### 予測結果
ハイパーパラメータチューニング後の予測結果も精度が0.83と悪い数字ではない
学習曲線を見ても回数を重ねるごとにScoreが上がっていることから、問題なく学習が進んでいることが確認できる

### pycaretを使用してみた感想
データの前処理からモデル作成、ハイパーパラメータチューニング、予測までを**数行**で行うころができる
またモデルの比較も1つの関数で行うことができるので、モデル比較の時間もかなり短縮することができる
機械学習の知識がなくても簡単にPoCまでのフェーズに到達することができると思う